#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNINE_Fee_Management
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cNine_Fee_Management")]
	public partial class MyDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertstaff(staff instance);
    partial void Updatestaff(staff instance);
    partial void Deletestaff(staff instance);
    #endregion
		
		public MyDBDataContext() : 
				base(global::CNINE_Fee_Management.Properties.Settings.Default.cNine_Fee_ManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<staff> staffs
		{
			get
			{
				return this.GetTable<staff>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_insertStaff")]
		public int st_insertStaff([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fatherName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EPFID", DbType="VarChar(12)")] string ePFID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateOfBirth", DbType="VarChar(11)")] string dateOfBirth, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateOfJoin", DbType="VarChar(11)")] string dateOfJoin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="VarChar(50)")] string emailAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string phone1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string phone2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> post, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="TinyInt")] System.Nullable<byte> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, fatherName, ePFID, dateOfBirth, dateOfJoin, emailAddress, phone1, phone2, post, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getStaff")]
		public ISingleResult<st_getStaffResult> st_getStaff()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getStaffResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_deleteStaff")]
		public int st_deleteStaff([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StaffID", DbType="Int")] System.Nullable<int> staffID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), staffID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_updateStaff")]
		public int st_updateStaff([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FatherName", DbType="VarChar(50)")] string fatherName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EPFID", DbType="VarChar(12)")] string ePFID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateOfBirth", DbType="VarChar(11)")] string dateOfBirth, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateOfJoin", DbType="VarChar(11)")] string dateOfJoin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string emailAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string phone1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string phone2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string post, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> staffID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, fatherName, ePFID, dateOfBirth, dateOfJoin, emailAddress, phone1, phone2, post, status, staffID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.st_getStaffDetails")]
		public ISingleResult<st_getStaffDetailsResult> st_getStaffDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<st_getStaffDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.r_searchStaff")]
		public ISingleResult<r_searchStaffResult> r_searchStaff([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string data)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), data);
			return ((ISingleResult<r_searchStaffResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.staff")]
	public partial class staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _st_id;
		
		private string _st_name;
		
		private string _st_fatherName;
		
		private string _st_EPFID;
		
		private string _st_DOB;
		
		private string _st_DOJ;
		
		private string _st_emailAddress;
		
		private string _st_phone1;
		
		private string _st_phone2;
		
		private string _st_Post;
		
		private byte _st_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onst_idChanging(int value);
    partial void Onst_idChanged();
    partial void Onst_nameChanging(string value);
    partial void Onst_nameChanged();
    partial void Onst_fatherNameChanging(string value);
    partial void Onst_fatherNameChanged();
    partial void Onst_EPFIDChanging(string value);
    partial void Onst_EPFIDChanged();
    partial void Onst_DOBChanging(string value);
    partial void Onst_DOBChanged();
    partial void Onst_DOJChanging(string value);
    partial void Onst_DOJChanged();
    partial void Onst_emailAddressChanging(string value);
    partial void Onst_emailAddressChanged();
    partial void Onst_phone1Changing(string value);
    partial void Onst_phone1Changed();
    partial void Onst_phone2Changing(string value);
    partial void Onst_phone2Changed();
    partial void Onst_PostChanging(string value);
    partial void Onst_PostChanged();
    partial void Onst_statusChanging(byte value);
    partial void Onst_statusChanged();
    #endregion
		
		public staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int st_id
		{
			get
			{
				return this._st_id;
			}
			set
			{
				if ((this._st_id != value))
				{
					this.Onst_idChanging(value);
					this.SendPropertyChanging();
					this._st_id = value;
					this.SendPropertyChanged("st_id");
					this.Onst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string st_name
		{
			get
			{
				return this._st_name;
			}
			set
			{
				if ((this._st_name != value))
				{
					this.Onst_nameChanging(value);
					this.SendPropertyChanging();
					this._st_name = value;
					this.SendPropertyChanged("st_name");
					this.Onst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_fatherName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string st_fatherName
		{
			get
			{
				return this._st_fatherName;
			}
			set
			{
				if ((this._st_fatherName != value))
				{
					this.Onst_fatherNameChanging(value);
					this.SendPropertyChanging();
					this._st_fatherName = value;
					this.SendPropertyChanged("st_fatherName");
					this.Onst_fatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_EPFID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string st_EPFID
		{
			get
			{
				return this._st_EPFID;
			}
			set
			{
				if ((this._st_EPFID != value))
				{
					this.Onst_EPFIDChanging(value);
					this.SendPropertyChanging();
					this._st_EPFID = value;
					this.SendPropertyChanged("st_EPFID");
					this.Onst_EPFIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_DOB", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string st_DOB
		{
			get
			{
				return this._st_DOB;
			}
			set
			{
				if ((this._st_DOB != value))
				{
					this.Onst_DOBChanging(value);
					this.SendPropertyChanging();
					this._st_DOB = value;
					this.SendPropertyChanged("st_DOB");
					this.Onst_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_DOJ", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string st_DOJ
		{
			get
			{
				return this._st_DOJ;
			}
			set
			{
				if ((this._st_DOJ != value))
				{
					this.Onst_DOJChanging(value);
					this.SendPropertyChanging();
					this._st_DOJ = value;
					this.SendPropertyChanged("st_DOJ");
					this.Onst_DOJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_emailAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string st_emailAddress
		{
			get
			{
				return this._st_emailAddress;
			}
			set
			{
				if ((this._st_emailAddress != value))
				{
					this.Onst_emailAddressChanging(value);
					this.SendPropertyChanging();
					this._st_emailAddress = value;
					this.SendPropertyChanged("st_emailAddress");
					this.Onst_emailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_phone1", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string st_phone1
		{
			get
			{
				return this._st_phone1;
			}
			set
			{
				if ((this._st_phone1 != value))
				{
					this.Onst_phone1Changing(value);
					this.SendPropertyChanging();
					this._st_phone1 = value;
					this.SendPropertyChanged("st_phone1");
					this.Onst_phone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_phone2", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string st_phone2
		{
			get
			{
				return this._st_phone2;
			}
			set
			{
				if ((this._st_phone2 != value))
				{
					this.Onst_phone2Changing(value);
					this.SendPropertyChanging();
					this._st_phone2 = value;
					this.SendPropertyChanged("st_phone2");
					this.Onst_phone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_Post", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string st_Post
		{
			get
			{
				return this._st_Post;
			}
			set
			{
				if ((this._st_Post != value))
				{
					this.Onst_PostChanging(value);
					this.SendPropertyChanging();
					this._st_Post = value;
					this.SendPropertyChanged("st_Post");
					this.Onst_PostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_status", DbType="TinyInt NOT NULL")]
		public byte st_status
		{
			get
			{
				return this._st_status;
			}
			set
			{
				if ((this._st_status != value))
				{
					this.Onst_statusChanging(value);
					this.SendPropertyChanging();
					this._st_status = value;
					this.SendPropertyChanged("st_status");
					this.Onst_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class st_getStaffResult
	{
		
		private int _ID;
		
		private string _Name;
		
		public st_getStaffResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class st_getStaffDetailsResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _EPFID;
		
		private string _FatherNamme;
		
		private string _DateOfBirth;
		
		private string _DateOfJoin;
		
		private string _EmailAddress;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Post;
		
		private string _Status;
		
		public st_getStaffDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPFID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string EPFID
		{
			get
			{
				return this._EPFID;
			}
			set
			{
				if ((this._EPFID != value))
				{
					this._EPFID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherNamme", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FatherNamme
		{
			get
			{
				return this._FatherNamme;
			}
			set
			{
				if ((this._FatherNamme != value))
				{
					this._FatherNamme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this._DateOfBirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfJoin", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string DateOfJoin
		{
			get
			{
				return this._DateOfJoin;
			}
			set
			{
				if ((this._DateOfJoin != value))
				{
					this._DateOfJoin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this._Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this._Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Post
		{
			get
			{
				return this._Post;
			}
			set
			{
				if ((this._Post != value))
				{
					this._Post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class r_searchStaffResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _FatherName;
		
		private string _EPFID;
		
		private string _DateOfBirth;
		
		private string _DateOfJoin;
		
		private string _EmailAddress;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Post;
		
		private string _Status;
		
		public r_searchStaffResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this._FatherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPFID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string EPFID
		{
			get
			{
				return this._EPFID;
			}
			set
			{
				if ((this._EPFID != value))
				{
					this._EPFID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this._DateOfBirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfJoin", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string DateOfJoin
		{
			get
			{
				return this._DateOfJoin;
			}
			set
			{
				if ((this._DateOfJoin != value))
				{
					this._DateOfJoin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this._Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this._Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Post
		{
			get
			{
				return this._Post;
			}
			set
			{
				if ((this._Post != value))
				{
					this._Post = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
